version: "3"
services:
  application:
    image: spring-thymeleaf-docker
    ports:
      - "9090:8080"
    networks:
      - springboot-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE = employee

networks:
  springboot-net:
