spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/employee
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update